#!/usr/bin/env ruby
require 'thor'
require 'bitcoin'
require 'bitcoin/node/spv'

class Bitcoinrbd < Thor

  option :mode, default: 'spv'
  option :network, default: 'mainnet'
  desc 'start', 'start bitcoinrbd daemon process'
  def start
    raise ArgumentError, 'currently only support spv mode.' unless options[:mode] == 'spv'
    Bitcoin.chain_params = network.to_sym
    FileUtils.mkdir_p(Bitcoin.base_dir)
    execute_daemon(['start'])
  end

  option :mode, default: 'spv'
  option :network, default: 'mainnet'
  desc 'stop', 'start bitcoinrbd daemon process'
  def stop
    execute_daemon(['stop'])
  end

  def execute_daemon(cmd_args)
    Bitcoin::Nodes::SPV.spawn!({working_dir: Bitcoin.base_dir,
                                     log_file: "#{Bitcoin.base_dir}/bitcoinrbd.log",
                                     pid_file: "#{Bitcoin.base_dir}/bitcoinrbd.pid",
                                     sync_log: true,
                                     singleton: true}, cmd_args)
  end

end

Bitcoinrbd.start(ARGV)